### ISSUE TITLE
Improve: Open by its ID

### ISSUE THREAD

**Issue by MathieuMart** [wide/modulus-modal#13]
It would be great to be able to initialize multiple modals with a generic JS code (with Modal from '@wide/modulus-modal') and open a modal with its ID.

**Comment by robiseb** [comment]
Hi @MatHackDev 

You already can do it.  

When using `data-modal` HTML attribute, instead using a modulus component name as value, use an ID selector.

```html
<button data-modal="#modalOne">Open Modal One</button>

<div class="modal" role="dialog" id="modalOne" is="modal">
  ...
</div>
```

Best regards
